### ISSUE TITLE
Somebody's spamming

### ISSUE THREAD

**Issue by wizzwizz4** [erangell/RMChipTester#6]
Somebody edited an answer on Retrocomputing Stack Exchange to insert a link to this program and a request for help. I would like to remind you that questions should be posted as questions &ndash; on the correct sites &ndash; and if you know who is posting this spam please make them stop.

**Comment by erangell** [comment]
Original post to Retrocomputing Stack Exchange:
I'm looking to see if there exists code to exercise the functions of the 6522 chip to validate that it functions correctly after installation on a board for the Apple 2 series computer.  The Mockingboard demo disks exercise the communications and some timer and interrupt functions but not everything.  I have Rodnay Zaks book 6502 Applications (Isbn 0-89588-015-6) which walks through the functions available so I can write my own test code but I want to see if this wheel has already been invented first.   

Update added 12/30/2018:
Update: I have built a test harness using an Arduino Mega with a Data Logger Shield and am able to test the output ports but am having difficulty getting tests for input ports to pass.  Help/PRs are appreciated: https://github.com/erangell/RMChipTester
-- | --
